version: "3"
services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./sdn_nginx:/etc/nginx/conf.d
    restart: "unless-stopped" 

  jenkins:
    build: ./sdn_jenkins_config
    container_name: jenkins
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./sdn_jenkins:/var/jenkins_home
      - ~/sdn_jenkins_config:/root/.ssh
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    expose:
      - "8080"
      - "50000"
    restart: "unless-stopped"

  redmine:
    build: ./sdn_redmine
    container_name: redmine
    expose:
      - 9100
    ports:
      - 58000:3000
    volumes:
      - ./sdn_redmine/files:/usr/src/redmine/files
      - ./sdn_redmine/plugins:/usr/src/redmine/plugins
      - ./sdn_redmine/themes:/usr/src/redmine/public/themes
      - ./sdn_redmine/project:/usr/src/redmine/project
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey
    restart: "unless-stopped"
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./sdn_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    expose:
      - 3306 

  grafana:
    image: grafana/grafana:8.2.6
    container_name: grafana
    volumes:
      - ./sdn_grafana/grafana:/var/lib/grafana
      - ./sdn_grafana/configuration/defaults.ini:/usr/share/grafana/conf/defaults.ini
    expose:
      - 3000
    ports:
      - 53000:3000
    user: '472'

  prometheus:
    image: prom/prometheus:main
    container_name : prometheus
    user: root
    volumes:
      - ./sdn_prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

