version: "3"
services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./sdn_nginx:/etc/nginx/conf.d
    restart: "unless-stopped" 

  jenkins:
    platform: linux/arm64
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    user: root
    volumes:
      - ./sdn_jenkins:/var/jenkins_home
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    expose:
      - "8080"
      - "50000"
    restart: "unless-stopped"

  redmine:
    image: sdn_redmine:5.0
    restart: always
    container_name: redmine
    ports:
      - 58000:3000
    volumes:
      - ./sdn_redmine/files:/usr/src/redmine/files
      - ./sdn_redmine/plugins:/usr/src/redmine/plugins
      - ./sdn_redmine/themes:/usr/src/redmine/public/themes
      - ./sdn_redmine/project:/usr/src/redmine/project
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey
    restart: "unless-stopped"
  db:
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    volumes:
      - ./sdn_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    expose:
      - 3306 

  grafana:
    image: grafana/grafana:8.2.6
    volumes:
      - ./sdn_grafana:/var/lib/grafana
    expose:
      - 3000
    ports:
      - 53000:3000
    user: '472'

